# è®¢é˜…é…ç½®
proxy-providers:
  freeCloud:
    type: http
    url: "è®¢é˜…è¿æ¥æ”¾è¿™é‡Œ"
    interval: 3600
    path: ./providers/freecloud.yaml
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204
  
  other:
    type: http
    url: "è®¢é˜…è¿æ¥æ”¾è¿™é‡Œ"
    interval: 3600
    path: ./providers/other.yaml
    # proxy: ğŸš€ ä»£ç†é€‰æ‹©   # å¦‚æœéœ€è¦è®¾ç½®é€šè¿‡ä»£ç†æ›´æ–°å–æ¶ˆæ³¨é‡Š
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204


# æç®€ç‰ˆ Clash é…ç½®
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false
unified-delay: true

# æ§åˆ¶é¢æ¿
external-controller: 127.0.0.1:9090
secret: ""
external-ui-name: zashboard
external-ui: "./ui"
external-ui-url: "https://gh-proxy.com/https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

geo-update-interval: 24
geox-url:
  geoip: https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb
  asn: https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb

# DNS
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

tun:
  enable: false # ä¿®æ”¹ä¸ºfalseï¼Œç”±é¢æ¿æ¥åˆ‡æ¢æ˜¯å¦å¼€å¯tun  
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true


proxy-groups:
  - name: ğŸš€ ä»£ç†é€‰æ‹©
    type: select
    proxies:
      - ğŸ“¦ freeCloud
      - ğŸ“¦ other
      - DIRECT
  
  - name: ğŸ“¦ freeCloud
    type: select
    use:
      - freeCloud
  
  - name: ğŸ“¦ other
    type: select
    use:
      - other
      
  - name: ğŸ¤– äººå·¥æ™ºèƒ½
    type: select
    use:
      - freeCloud
    filter: '^(?=.*((?i)è½åœ°|å®¶å®½)).*$'

# è®¢é˜…è§„åˆ™
rule-providers:
  ai_non_ip:
    type: http
    behavior: classical
    interval: 43200
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./rule_set/sukkaw_ruleset/ai_non_ip.txt

rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - GEOIP,CN,DIRECT
  - RULE-SET,ai_non_ip,ğŸ¤– äººå·¥æ™ºèƒ½
  - MATCH,ğŸš€ ä»£ç†é€‰æ‹©
