# æç®€ç‰ˆ Clash é…ç½®
mixed-port: 7897
allow-lan: false
mode: rule
log-level: info
ipv6: false
unified-delay: true

# æ§åˆ¶é¢æ¿
external-controller: 127.0.0.1:9090
external-ui: zashboard 
secret: ""

tun:
  enable: false # ä¿®æ”¹ä¸ºfalseï¼Œç”±é¢æ¿æ¥åˆ‡æ¢æ˜¯å¦å¼€å¯tun  

geo-update-interval: 24
geox-url:
  geoip: https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb
  asn: https://gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb

# DNS
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 223.5.5.5
    - 119.29.29.29

# è®¢é˜…é…ç½®
proxy-providers:
  å®¶é‡Œäº‘:
    type: http
    url: "è¿™é‡Œæ”¾ç¬¬ä¸€ä¸ªè®¢é˜…é“¾æ¥"
    interval: 3600
    path: ./providers/homcloud.yaml
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204
  
  å…è´¹äº‘:
    type: http
    url: "è¿™é‡Œæ”¾ç¬¬äºŒä¸ªè®¢é˜…é“¾æ¥"
    interval: 3600
    path: ./providers/freecloud.yaml
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: ğŸš€ ä»£ç†é€‰æ‹©
    type: select
    proxies:
      - ğŸ“¦ å®¶é‡Œäº‘
      - ğŸ“¦ å…è´¹äº‘
      - DIRECT
  
  - name: ğŸ“¦ å®¶é‡Œäº‘
    type: select
    use:
      - å®¶é‡Œäº‘
  
  - name: ğŸ“¦ å…è´¹äº‘
    type: select
    use:
      - å…è´¹äº‘

rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ğŸš€ ä»£ç†é€‰æ‹©
